[pytest]
testpaths = tests
addopts = -ra
filterwarnings =
    error::RuntimeWarning
    error::ResourceWarning
    ignore:on_event is deprecated:DeprecationWarning
    ignore:The `name` is not the first parameter anymore:DeprecationWarning
